# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=15)),
                ('faixa', models.IntegerField(choices=[(1, 'Branca'), (2, 'Cinza / Branca'), (3, 'Cinza'), (4, 'Cinza / Preta'), (5, 'Amarela Branca'), (6, 'Amarela'), (7, 'Amarela / Preta'), (8, 'Laranja / Branca'), (9, 'Laranja'), (10, 'Laranja / Preta'), (11, 'Verde / Branca'), (12, 'Verde'), (13, 'Verde / Preta'), (14, 'Azul'), (15, 'Roxa'), (16, 'Marrom'), (17, 'Preta'), (18, 'Vermelha / Preta'), (19, 'Vermelha / Branca'), (20, 'Vermelha')], default=1)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Academia')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('categoria_peso', models.IntegerField(choices=[(1, 'Galo'), (2, 'Pluma'), (3, 'Pena'), (4, 'Leve'), (5, 'Médio'), (6, 'Meio Pesado'), (7, 'Pesado'), (8, 'Super Pesado'), (9, 'Pesadíssimo')], default=1)),
                ('categoria_idade', models.IntegerField(choices=[(1, 'Pré-Mirin'), (2, 'Mirin'), (3, 'Infantil'), (4, 'Infanto Juvenil'), (5, 'Adulto'), (6, 'Master')], default=5)),
                ('absoluto', models.BooleanField(default=False)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('valor_absoluto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atleta')),
            ],
        ),
        migrations.AddField(
            model_name='academia',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipe'),
        ),
    ]
