# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='pago_absoluto',
            field=models.BooleanField(default=False, verbose_name='absoluto pago'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pago_inscricao',
            field=models.BooleanField(default=False, verbose_name='inscrição paga'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='categoria_idade',
            field=models.IntegerField(choices=[(1, 'Pré-Mirin'), (2, 'Mirin'), (3, 'Infantil'), (4, 'Infanto Juvenil'), (5, 'Adulto'), (6, 'Master')], default=5, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='categoria_peso',
            field=models.IntegerField(choices=[(1, 'Galo'), (2, 'Pluma'), (3, 'Pena'), (4, 'Leve'), (5, 'Médio'), (6, 'Meio Pesado'), (7, 'Pesado'), (8, 'Super Pesado'), (9, 'Pesadíssimo')], default=1, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='valor da inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='valor_absoluto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='valor absoluto'),
        ),
    ]
