# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171005_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinacaoAbsoluto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('faixa', models.IntegerField(choices=[(1, 'Branca'), (2, 'Cinza / Branca'), (3, 'Cinza'), (4, 'Cinza / Preta'), (5, 'Amarela Branca'), (6, 'Amarela'), (7, 'Amarela / Preta'), (8, 'Laranja / Branca'), (9, 'Laranja'), (10, 'Laranja / Preta'), (11, 'Verde / Branca'), (12, 'Verde'), (13, 'Verde / Preta'), (14, 'Azul'), (15, 'Roxa'), (16, 'Marrom'), (17, 'Preta'), (18, 'Vermelha / Preta'), (19, 'Vermelha / Branca'), (20, 'Vermelha')])),
                ('idade', models.IntegerField(choices=[(1, 'Pré-Mirin'), (2, 'Mirin'), (3, 'Infantil'), (4, 'Infanto Juvenil'), (7, 'Juvenil'), (5, 'Adulto'), (6, 'Master')])),
                ('inscricao', models.ManyToManyField(to='core.Inscricao')),
            ],
            options={
                'verbose_name': 'combinação absoluto',
                'verbose_name_plural': 'combinações absoluto',
            },
        ),
        migrations.RemoveField(
            model_name='confronto',
            name='inscricao',
        ),
        migrations.DeleteModel(
            name='Confronto',
        ),
    ]
