# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171007_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('faixa', models.IntegerField(choices=[(1, 'Branca'), (2, 'Cinza / Branca'), (3, 'Cinza'), (4, 'Cinza / Preta'), (5, 'Amarela Branca'), (6, 'Amarela'), (7, 'Amarela / Preta'), (8, 'Laranja / Branca'), (9, 'Laranja'), (10, 'Laranja / Preta'), (11, 'Verde / Branca'), (12, 'Verde'), (13, 'Verde / Preta'), (14, 'Azul'), (15, 'Roxa'), (16, 'Marrom'), (17, 'Preta'), (18, 'Vermelha / Preta'), (19, 'Vermelha / Branca'), (20, 'Vermelha')])),
                ('idade', models.IntegerField(choices=[(1, 'Pré-Mirin'), (2, 'Mirin'), (3, 'Infantil'), (4, 'Infanto Juvenil'), (7, 'Juvenil'), (5, 'Adulto'), (6, 'Master')])),
            ],
            options={
                'verbose_name': 'chave',
                'verbose_name_plural': 'chaves',
            },
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('tempo', models.TimeField()),
                ('etapa', models.IntegerField(choices=[(1, 'Oitava de Final'), (2, 'Quarta de Final'), (3, 'Semi de Final'), (4, 'Final'), (5, 'Outra')], default=5)),
                ('encerrada', models.BooleanField(default=False)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chave')),
            ],
            options={
                'verbose_name': 'combate',
                'verbose_name_plural': 'combates',
            },
        ),
        migrations.CreateModel(
            name='CombateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto', models.IntegerField(default=0)),
                ('vantagem', models.IntegerField(default=0)),
                ('punicao', models.IntegerField(default=0)),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Combate')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Inscricao')),
            ],
            options={
                'verbose_name': 'informação do combate',
                'verbose_name_plural': 'informações dos combates',
            },
        ),
        migrations.CreateModel(
            name='CombateResultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vitoria', models.IntegerField(choices=[(1, 'Finalização'), (2, 'Pontuação'), (3, 'Desistencia'), (4, 'W.O'), (5, 'Outro')], default=1)),
                ('tempo', models.TimeField()),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CombateInfo')),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Combate')),
            ],
            options={
                'verbose_name': 'resultado do combate',
                'verbose_name_plural': 'resultados dos combates',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absoluto', models.BooleanField(default=False)),
                ('pontos', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=100)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Inscricao')),
            ],
            options={
                'verbose_name': 'resultado',
                'verbose_name_plural': 'resultados',
            },
        ),
        migrations.AddField(
            model_name='combate',
            name='inscricao',
            field=models.ManyToManyField(through='core.CombateInfo', to='core.Inscricao'),
        ),
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together=set([('atleta', 'absoluto')]),
        ),
    ]
