# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171010_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
