# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171014_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combate',
            name='data',
        ),
        migrations.RemoveField(
            model_name='combate',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='combate',
            name='tempo',
        ),
    ]
